name: Wine for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install bison
      run: brew install bison
    - name: bison path
      run: export PATH="/usr/local/opt/bison/bin:$PATH"' >> /Users/runner/.bash_profile
    - name: tar xvf
      run: tar xvf wine.tar.xz
    - name: cd wine
      run: cd wine-6.18
    - name: ls
      run: ls
    - name: configure
      run: cd wine-6.18 && ./configure --enable-win64
    - name: make
      run: make
    - name: make install
      run: make install
