name: Wine for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install bison
      run: brew reinstall --formula bison
    - name: bison path
      run: export PATH="/usr/local/opt/bison/bin:$PATH" >> /Users/runner/.bash_profile
    - name: bison ex
      run: export LDFLAGS="-L/usr/local/opt/bison/lib"
    - name: excising
      run: brew unlink bison && echo ‘export PATH="/usr/local/opt/bison/bin:$PATH"’ >> ~/.bash_profile && export LDFLAGS="-L/usr/local/opt/bison/lib" && source ~/.bash_profile && brew link bison --force
    - name: tar xvf
      run: tar xvf wine.tar.xz
    - name: cd wine
      run: cd wine-6.18
    - name: ls
      run: ls
    - name: install ports
      run： sudo installer -pkg MacPorts.pkg -target /
    - name: install bison 3
      run: port install bison
    - name: configure
      run: cd wine-6.18 && ./configure --enable-win64
    - name: make
      run: make
    - name: make install
      run: make install
