name: Wine for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: install ports
      run: sudo installer -pkg MacPorts.pkg -target /
    - name: install bison
      run: sudo port install rdepof:wine-devel +universal +x11
    - name: tar xvf
      run: tar xvf wine.tar.xz
    - name: cd wine
      run: cd wine-6.18
    - name: ls
      run: ls
    - name: configure
      run: cd wine-6.18 && ./configure --enable-win64
    - name: make
      run: make -j8
    - name: make install
      run: make install
