name: Wine for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: tar xvf
      run: tar xvf wine.tar.xz
    - name: cd wine
      run: cd wine-6.18
    - name: ls
      run: ls
    - name: configure
      run: ./configure -mingw64
    - name: make
      run: make -j8
    - name: make install
      run: make install
